[project]
name = "AuRoRA"
version = "0.1.3"
description = "Autonomous Rover Robotic Assistant"
readme = "README.md"
requires-python = "==3.10.12"
dependencies = [
    "flask>=3.1.2",
    "python-dotenv>=1.2.1",
    "python-telegram-bot>=22.6",
    "slack-bolt>=1.27.0",
    "slack-sdk>=3.40.0",
]
