[project]
name = "AuRoRA"
version = "0.1.3"
description = "Autonomous Rover Robotic Assistant"
readme = "README.md"
requires-python = "==3.10.12"
dependencies = [
    "jetson-stats>=4.3.2",
    "psutil>=7.2.2",
    "pyyaml>=6.0.3",
]
